const {chromium}=require(process.env.FFB_PLAYWRIGHT||'playwright');
const fs=require('fs');
fs.mkdirSync('work/ui-qa',{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.FFB_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const wait=async fn=>{const end=Date.now()+30000;while(Date.now()<end){if(await page.evaluate(fn))return;await page.waitForTimeout(100)}throw Error('State wait timed out: '+fn.toString())};
 await page.goto(process.env.FFB_BASE_URL||'http://127.0.0.1:8765');await page.locator('#play:enabled').waitFor({timeout:30000});
 await page.route('**/api/control',async route=>{if(route.request().postDataJSON()?.action==='reset'){const response=await route.fetch();await new Promise(resolve=>setTimeout(resolve,350));await route.fulfill({response})}else await route.continue()});
 await page.locator('#reset').click();await page.locator('#kind:disabled').waitFor();await page.locator('#kind:enabled').waitFor();await page.unroute('**/api/control');await wait(async()=>{const s=await(await fetch('/api/live')).json();return s.sim_ms===0&&s.stimulus.kind==='blank'});
 await page.selectOption('#kind','grating');await page.selectOption('#eye','L');await page.selectOption('#duration','500');
 await wait(async()=>{const s=await(await fetch('/api/live')).json();return s.stimulus.kind==='grating'&&s.stimulus.eye==='L'});
 await page.locator('#play').click();await wait(async()=>{const s=await(await fetch('/api/live')).json();return s.sim_ms===500&&s.status==='paused'});
 let data=await page.evaluate(async()=>await(await fetch('/api/live')).json());
 if(!data.history.some(s=>s.spikes>0))throw Error('No response to applied grating');
 const initialRun=data.run_id;
 await page.locator('#search').fill('T4a');await page.locator('#searchButton').click();await page.locator('#searchResults button').first().waitFor();await page.locator('#searchResults button').first().click();
 await wait(async()=>!!(await(await fetch('/api/live')).json()).probe);
 await page.locator('#pulseDuration').fill('20');await page.locator('#pulseAmplitude').fill('1.5');await page.locator('#pulseProbe').click();
 await wait(async()=>{const s=await(await fetch('/api/live')).json();return s.sim_ms>=620&&s.status==='paused'});
 await page.waitForFunction(()=>document.querySelector('#simtime').textContent==='620');await page.screenshot({path:'work/ui-qa/console-response.png',fullPage:true});
 await page.selectOption('#kind','paint');await wait(async()=>(await(await fetch('/api/live')).json()).stimulus.kind==='paint');
 await page.locator('#stimulus').scrollIntoViewIfNeeded();const canvas=await page.locator('#stimulus').boundingBox();await page.mouse.move(canvas.x+canvas.width*.2,canvas.y+canvas.height*.4);await page.mouse.down();await page.mouse.move(canvas.x+canvas.width*.8,canvas.y+canvas.height*.6,{steps:12});await page.mouse.up();
 await wait(async()=>(await(await fetch('/api/live')).json()).stimulus.paint.filter(v=>v>0).length>10);
 await page.locator('#step').click();await wait(async()=>(await(await fetch('/api/live')).json()).sim_ms===640);
 await page.selectOption('#kind','spot');await page.locator('#stimulus').click({position:{x:60,y:80}});
 await wait(async()=>{const s=await(await fetch('/api/live')).json();return s.stimulus.kind==='spot'&&Math.abs(s.stimulus.spot_x-.5)>.1});
 await page.selectOption('#duration','5000');await page.locator('#play').click();await wait(async()=>(await(await fetch('/api/live')).json()).status==='running');await page.locator('#pause').click();
 await wait(async()=>(await(await fetch('/api/live')).json()).status==='paused');
 const paused=await page.evaluate(async()=>(await(await fetch('/api/live')).json()).sim_ms);await page.waitForTimeout(600);
 if(paused!==await page.evaluate(async()=>(await(await fetch('/api/live')).json()).sim_ms))throw Error('Pause did not hold');
 await page.locator('#finish').click();await wait(async()=>{const s=await(await fetch('/api/live')).json();return (await(await fetch('/api/runs/'+s.run_id+'/manifest')).json()).status==='complete'});
 await page.waitForFunction(id=>[...document.querySelector('#record').options].some(o=>o.value===id),initialRun);
 await page.selectOption('#record',initialRun);await page.locator('#play:disabled').waitFor();await page.selectOption('#record','live');await page.locator('#reset').click();
 await wait(async()=>(await(await fetch('/api/live')).json()).sim_ms===0);
 await page.setViewportSize({width:820,height:1180});await page.screenshot({path:'work/ui-qa/console-narrow.png',fullPage:true});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Horizontal overflow at 820px');
 if(errors.length)throw Error(errors.join('\n'));
 fs.writeFileSync(process.env.FFB_QA_OUTPUT||'work/ui-qa/browser-smoke.json',JSON.stringify({passed:true,run_id:initialRun,checks:['reset locks controls until acknowledged','grating input','neural response','neuron search/probe','single-neuron pulse','manual paint','single step','spot placement','pause holds','saved record','archive controls disabled','reset','820px layout'],page_errors:errors},null,2));
 console.log('PASS',initialRun,'13 interaction checks');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
