'use strict';
const $=id=>document.getElementById(id), fmt=n=>Number(n).toLocaleString();
let data, selected, nodes=new Map(), projected=[], yaw=0,pitch=-.1,zoom=1,drag=null,selectionRequest=0,searchRequest=0;
const canvas=$('brain'),ctx=canvas.getContext('2d');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function get(path){const r=await fetch(path);if(!r.ok){let message=`Request failed (${r.status})`;try{message=(await r.json()).error||message}catch{}throw Error(message)}return r.json()}
function notice(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error)}
function project(xyz){const [x,y,z]=xyz,xx=x*Math.cos(yaw)-y*Math.sin(yaw),yy=x*Math.sin(yaw)+y*Math.cos(yaw),zz=z*Math.cos(pitch)-yy*Math.sin(pitch),depth=z*Math.sin(pitch)+yy*Math.cos(pitch);const w=canvas.clientWidth,h=canvas.clientHeight,scale=Math.min(w*.40,h*.39)*zoom;return {x:w/2+xx*scale,y:h/2+zz*scale,z:depth}}
function visible(n){return $('filter').value==='all'||($('filter').value==='input'?n.experiment_input:String(n.role)===$('filter').value)}
function arrow(a,b,color,width){if(!a||!b)return;const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy);if(len<5)return;ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();const t=.72,x=a.x+dx*t,y=a.y+dy*t,ang=Math.atan2(dy,dx);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-6*Math.cos(ang-.45),y-6*Math.sin(ang-.45));ctx.lineTo(x-6*Math.cos(ang+.45),y-6*Math.sin(ang+.45));ctx.fill()}
function schematic(w,h){
projected=[];ctx.font='11px -apple-system,sans-serif';ctx.textAlign='center';ctx.fillStyle='#9bafbd';ctx.fillText('PRESYNAPTIC PARTNERS →',w*.18,27);ctx.fillText('→ POSTSYNAPTIC PARTNERS',w*.82,27);
if(!selected){ctx.fillText('Select a neuron to inspect its connections',w/2,h/2);ctx.textAlign='left';return}
const center={x:w/2,y:h/2,node:selected.node},byId=new Map(selected.neighbors.map(n=>[n.id,n]));
for(const direction of ['incoming','outgoing']){const edges=selected.edges.filter(e=>e.direction===direction);edges.forEach((e,i)=>{const n=byId.get(e.neighbor),p={x:w*(direction==='incoming'?.18:.82),y:65+(h-120)*(i+.5)/Math.max(edges.length,1),node:n};projected.push(p);if($('connections').checked)arrow(direction==='incoming'?p:center,direction==='incoming'?center:p,direction==='incoming'?'#f4bc6a88':'#7de3ca88',1)})}
projected.push(center);for(const p of projected){const n=p.node;ctx.fillStyle=$('mode').value==='experiment'?(n.experiment_input?'#ff81d4':'#667888'):data.groups[n.role].color;ctx.beginPath();ctx.arc(p.x,p.y,n.id===selected.node.id?7:3.5,0,Math.PI*2);ctx.fill();if(n.experiment_input){ctx.strokeStyle='#ff81d4';ctx.beginPath();ctx.arc(p.x,p.y,n.id===selected.node.id?10:5.5,0,Math.PI*2);ctx.stroke()}ctx.fillStyle='#e6eef3';ctx.textAlign=p.x<w/2?'right':p.x>w/2?'left':'center';ctx.fillText(n.type,p.x+(p.x<w/2?-10:p.x>w/2?10:0),p.y+(p.x===w/2?-20:4))}
ctx.textAlign='center';ctx.fillStyle='#9bafbd';ctx.fillText(selected.node.id,w/2,h/2+26);ctx.fillText('Schematic connection layout · not anatomical positions',w/2,h-14);ctx.textAlign='left';
}
function draw(){if(!data)return;const ratio=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==Math.round(w*ratio)||canvas.height!==Math.round(h*ratio)){canvas.width=Math.round(w*ratio);canvas.height=Math.round(h*ratio)}ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,w,h);if($('layout').value==='schematic'){schematic(w,h);return}projected=[];const linked=new Set(selected&&$('connections').checked?selected.neighbors.map(n=>n.id):[]),coords=new Map();
for(const n of nodes.values()){if(!n.xyz)continue;if(!visible(n)&&!linked.has(n.id)&&n.id!==selected?.node.id)continue;const p={...project(n.xyz),node:n};coords.set(n.id,p);projected.push(p)}projected.sort((a,b)=>a.z-b.z);
if(selected&&$('connections').checked){ctx.globalAlpha=.75;for(const e of selected.edges)arrow(coords.get(e.source),coords.get(e.target),e.direction==='incoming'?'#f4bc6a':'#7de3ca',1);ctx.globalAlpha=1}
for(const p of projected){const n=p.node,isSelected=n.id===selected?.node.id,isLinked=linked.has(n.id),experiment=$('mode').value==='experiment';let color=experiment?(n.experiment_input?'#ff81d4':'#42505e'):data.groups[n.role].color;ctx.globalAlpha=isSelected||isLinked?1:experiment&&!n.experiment_input?.26:.65;ctx.fillStyle=color;ctx.beginPath();ctx.arc(p.x,p.y,isSelected?5:isLinked?3.3:n.experiment_input?2:1.65,0,Math.PI*2);ctx.fill();if(n.experiment_input||isSelected){ctx.strokeStyle=isSelected?'#fff':'#ff81d4';ctx.lineWidth=isSelected?1.5:.65;ctx.beginPath();ctx.arc(p.x,p.y,isSelected?8:3.1,0,Math.PI*2);ctx.stroke()}}
ctx.globalAlpha=1;ctx.font='11px -apple-system,sans-serif';ctx.fillStyle='#97acbb';ctx.fillText(`${fmt(projected.length)} visible landmarks`,12,h-16);if(selected?.node.xyz){const p=coords.get(selected.node.id);if(p){ctx.fillStyle='#e6eef3';ctx.fillText(`${selected.node.type} · selected`,Math.min(w-120,Math.max(8,p.x+12)),Math.max(35,p.y-12))}}
const base=project([0,0,0]);for(const [v,label,color]of [[[.22,0,0],'X','#f4bc6a'],[[0,.22,0],'Y','#7de3ca'],[[0,0,.22],'Z','#8b9bff']]){const p=project(v),origin={x:45,y:h-65},end={x:origin.x+(p.x-base.x)/zoom,y:origin.y+(p.y-base.y)/zoom};arrow(origin,end,color,1);ctx.fillStyle=color;ctx.fillText(label,end.x+3,end.y+3)}}
function nearest(x,y){let best=null,d=100;for(const p of projected){const v=(p.x-x)**2+(p.y-y)**2;if(v<d){d=v;best=p.node}}return best}
function filterChanged(){document.querySelectorAll('.role').forEach(e=>e.classList.toggle('active',e.dataset.role===$('filter').value));draw()}
async function select(id){const ticket=++selectionRequest;try{const result=await get('/api/network/neuron/'+encodeURIComponent(id));if(ticket!==selectionRequest)return;selected=result;nodes=new Map(data.points.map(n=>[n.id,n]));for(const n of [selected.node,...selected.neighbors])nodes.set(n.id,n);const n=selected.node,g=data.groups[n.role];$('selection').innerHTML=`<h3>${esc(n.type)}</h3><div class="id">${esc(n.id)}</div>${n.experiment_input?'<span class="badgetext">Experiment 2 input AND readout</span>':'<p class="small">Not selected as an Experiment 2 input or readout.</p>'}<dl><dt>Annotated superclass</dt><dd>${esc(n.superclass)}</dd><dt>Display grouping</dt><dd>${esc(g.name)}</dd><dt>Annotated side</dt><dd>${esc(n.side)}</dd><dt>Incoming partners</dt><dd>${fmt(result.incoming_count)}</dd><dt>Outgoing partners</dt><dd>${fmt(result.outgoing_count)}</dd><dt>Location source</dt><dd>${esc(n.location_source||'Not available')}</dd></dl><p class="small">${esc(g.description)}</p>${!n.xyz?'<p class="small">This neuron has no available landmark. It remains inspectable here, but we do not invent a dot position.</p>':''}`;
const map=new Map(result.neighbors.map(n=>[n.id,n]));$('neighbors').innerHTML=`<p class="small">Up to 20 per direction, ranked by ${esc(result.ranking)}. Neighbors remain visible when a group is filtered.</p>`+result.edges.map(e=>{const p=map.get(e.neighbor);return `<button data-node="${esc(p.id)}"><span>${e.direction==='incoming'?'↘ IN':'↗ OUT'} · ${esc(p.type)}<small>${esc(p.id)}</small></span><span>${e.contacts===null?esc(e.model_weight_mv.toFixed(3))+' mV':fmt(e.contacts)+' contacts'}<small>${e.contacts===null?'assumed model weight':'recorded anatomy'}</small></span></button>`}).join('');$('neighbors').querySelectorAll('button').forEach(b=>b.onclick=()=>select(b.dataset.node));notice(`${data.synthetic?'Synthetic teaching data':'MaleCNS anatomy'} · read-only view · ${result.note}`);draw()}catch(e){notice(e.message,true)}}
$('searchForm').onsubmit=async e=>{e.preventDefault();const ticket=++searchRequest;try{const rows=await get('/api/network/search?q='+encodeURIComponent($('search').value));if(ticket!==searchRequest)return;$('results').innerHTML=rows.length?rows.map(n=>`<button data-node="${esc(n.id)}">${esc(n.type)} · ${esc(n.side)} · ${esc(n.id)}${n.xyz?'':' · no location'}</button>`).join(''):'<p class="small">No matching neurons.</p>';$('results').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('results').innerHTML='';select(b.dataset.node)});if(rows.length===1){$('results').innerHTML='';select(rows[0].id)}}catch(e){notice(e.message,true)}};
canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false}};
canvas.onpointermove=e=>{const box=canvas.getBoundingClientRect();if(drag){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved ||= Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>4;if($('layout').value==='anatomy'){yaw+=dx*.008;pitch=Math.max(-1.4,Math.min(1.4,pitch+dy*.008));}drag.x=e.clientX;drag.y=e.clientY;draw()}else{const n=nearest(e.clientX-box.left,e.clientY-box.top);$('hover').textContent=n?`${n.type} · ${n.id} · ${data.groups[n.role].name}`:($('layout').value==='schematic'?'Click a neuron to inspect its connections':'Drag to rotate · click a dot to inspect')}};
canvas.onpointerup=e=>{if(drag&&!drag.moved){const b=canvas.getBoundingClientRect(),n=nearest(e.clientX-b.left,e.clientY-b.top);if(n)select(n.id)}drag=null};canvas.onpointercancel=()=>{drag=null};
$('reset').onclick=()=>{yaw=0;pitch=-.1;zoom=1;draw()};$('zoomIn').onclick=()=>{zoom=Math.min(5,zoom*1.25);draw()};$('zoomOut').onclick=()=>{zoom=Math.max(.5,zoom/1.25);draw()};$('layout').onchange=()=>{const schematic=$('layout').value==='schematic';canvas.parentElement.classList.toggle('schematic',schematic);$('hover').textContent=schematic?'Click a neuron to inspect its connections':'Drag to rotate · click a dot to inspect';$('filter').disabled=schematic;$('zoomIn').disabled=schematic;$('zoomOut').disabled=schematic;$('layoutNote').textContent=schematic?'Schematic: selected neuron in the center, incoming partners on the left, outgoing partners on the right. Reciprocal partners can appear on both sides. Positions are a diagram layout, not anatomy.':'Anatomical view: recorded cell landmarks, with a uniform coordinate transform.';draw()};$('filter').onchange=filterChanged;$('mode').onchange=draw;$('connections').onchange=draw;
new ResizeObserver(draw).observe(canvas);
(async()=>{try{data=await get('/api/network/overview');nodes=new Map(data.points.map(n=>[n.id,n]));$('dataset').textContent=data.synthetic?'Synthetic teaching graph':`${data.dataset} · real annotation data`;$('experimentCounts').textContent=`${fmt(data.input_count)} L1 inputs = ${fmt(data.readout_count)} readouts`;$('coverage').textContent=`${fmt(data.displayed)} sampled dots · ${fmt(data.positioned)} neurons have landmarks`;$('sampleNote').textContent=`${data.sample_note} ${fmt(data.missing_positions)} neurons lack landmarks. ${data.coordinate_note}`;$('totals').textContent=`${fmt(data.neurons)} neurons · ${fmt(data.directed_edges)} directed neuron pairs`;
$('roles').innerHTML=data.groups.map((g,i)=>`<button class="role" data-role="${i}"><strong><i style="background:${g.color}"></i>${esc(g.name)}</strong><b>${fmt(g.count)}</b><p>${esc(g.description)}</p><small>${fmt(g.located)} with landmarks · ${esc(g.classes.join(', ')||'Remaining annotation classes')}</small></button>`).join('');data.groups.forEach((g,i)=>{const option=document.createElement('option');option.value=i;option.textContent=g.name;$('filter').appendChild(option)});$('roles').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('layout').value='anatomy';$('layout').onchange();$('filter').value=b.dataset.role;filterChanged()});draw();await select(data.initial_neuron)}catch(e){notice(e.message,true)}})();
