const $=id=>document.getElementById(id);
let token='',atlas=null,state=null,archived=false,recordId=null,paint=Array(768).fill(0),spot={x:.5,y:.5},polling=false,controlsReady=false,projected=[],lastRuns=0,formLoaded=false,resetting=false;
const camera={yaw:.1,pitch:-.12,zoom:1},colors=['#69dfd0','#b0a1ff','#f5b36d'];
async function get(url){const r=await fetch(url);if(!r.ok)throw new Error(`Request ${r.status}`);return r.json()}
function message(text,error=false){$('message').textContent=text;$('message').classList.toggle('error',error)}
async function command(value){if(archived){message('Switch View to Live controls before sending input.',true);return}const isReset=value.action==='reset';if(isReset){resetting=true;render()}try{if(!token)token=(await get('/api/session')).token;let r=await fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json','X-FFB-Token':token},body:JSON.stringify(value)});if(r.status===403){token=(await get('/api/session')).token;r=await fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json','X-FFB-Token':token},body:JSON.stringify(value)})}const v=await r.json();if(!r.ok)throw new Error(v.error||'Control rejected');message(`Applied at ${v.applied_at_ms} ms · commands are recorded with the run.`);if(value.action==='reset'){paint.fill(0);spot={x:.5,y:.5};$('kind').value='blank';$('eye').value='both';$('gain').value=.6;$('contrast').value=.8;$('frequency').value=2;$('cycles').value=4;$('radius').value=.15;$('direction').value=1;labels()}await refresh();return true}catch(e){message(e.message,true);return false}finally{if(isReset){resetting=false;render()}}}
function stimulus(){return {kind:$('kind').value,eye:$('eye').value,gain:+$('gain').value,contrast:+$('contrast').value,frequency_hz:+$('frequency').value,cycles:+$('cycles').value,direction:+$('direction').value,spot_x:spot.x,spot_y:spot.y,spot_radius:+$('radius').value,paint}}
function loadForm(s){if(!s)return;paint=[...s.paint];spot={x:s.spot_x,y:s.spot_y};for(const [id,key] of Object.entries({kind:'kind',eye:'eye',gain:'gain',contrast:'contrast',frequency:'frequency_hz',cycles:'cycles',radius:'spot_radius',direction:'direction'}))$(id).value=s[key];labels()}
function labels(){$('gainValue').textContent=(+$('gain').value).toFixed(2);$('contrastValue').textContent=(+$('contrast').value).toFixed(2);$('frequencyValue').textContent=$('frequency').value+' Hz';$('cyclesValue').textContent=$('cycles').value;$('radiusValue').textContent=$('radius').value;$('inputEye').textContent=$('eye').value==='both'?'Both eyes':$('eye').value==='L'?'Left eye':'Right eye'}
let applyTimer;function applyStimulus(){labels();clearTimeout(applyTimer);applyTimer=setTimeout(()=>command({action:'stimulus',stimulus:stimulus()}),100)}
for(const id of ['kind','eye','direction','gain','contrast','frequency','cycles','radius'])$(id).addEventListener('input',applyStimulus);
async function advance(value){clearTimeout(applyTimer);if(await command({action:'stimulus',stimulus:stimulus()}))await command(value)}
$('play').onclick=()=>advance({action:'play',duration_ms:+$('duration').value});$('pause').onclick=()=>command({action:'pause'});$('step').onclick=()=>advance({action:'step',duration_ms:20});$('reset').onclick=()=>{clearTimeout(applyTimer);command({action:'reset'})};$('finish').onclick=()=>command({action:'finish'});
function sendPulse(single=false){const v={action:'pulse',amplitude:+$('pulseAmplitude').value,duration_ms:+$('pulseDuration').value};if(single){if(!state?.probe)return;v.body_id=state.probe.id}else v.group=$('pulseGroup').value;advance(v)}
$('pulse').onclick=()=>sendPulse();$('pulseProbe').onclick=()=>sendPulse(true);
$('clearPaint').onclick=()=>{paint.fill(0);$('kind').value='paint';drawInput(paint);applyStimulus()};
function canvas(id){const c=$(id),dpr=window.devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;if(c.width!==Math.round(w*dpr)||c.height!==Math.round(h*dpr)){c.width=Math.round(w*dpr);c.height=Math.round(h*dpr)}const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,w,h);return {c,x,w,h}}
function drawInput(values){const {x,w,h}=canvas('stimulus');for(let j=0;j<24;j++)for(let i=0;i<32;i++){let v=Math.max(0,Math.min(255,Math.round((values[j*32+i]||0)*255)));x.fillStyle=`rgb(${v},${v},${v})`;x.fillRect(i*w/32,j*h/24,Math.ceil(w/32),Math.ceil(h/24))}x.strokeStyle='#67dacb55';x.lineWidth=.5;for(let i=0;i<=32;i++){x.beginPath();x.moveTo(i*w/32,0);x.lineTo(i*w/32,h);x.stroke()}for(let i=0;i<=24;i++){x.beginPath();x.moveTo(0,i*h/24);x.lineTo(w,i*h/24);x.stroke()}}
let painting=false,priorPaint=null;
function paintAt(e){if(!controlsReady||archived)return;const r=$('stimulus').getBoundingClientRect(),u=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),v=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));if($('kind').value!=='paint'){$('kind').value='spot';spot={x:u,y:v};applyStimulus();return}const px=Math.round(u*31),py=Math.round(v*23),from=priorPaint||[px,py],n=Math.max(1,Math.abs(px-from[0]),Math.abs(py-from[1]));for(let t=0;t<=n;t++){let ix=Math.round(from[0]+(px-from[0])*t/n),iy=Math.round(from[1]+(py-from[1])*t/n);paint[iy*32+ix]=e.buttons===2?0:1}priorPaint=[px,py];drawInput(paint);applyStimulus()}
$('stimulus').onpointerdown=e=>{painting=true;priorPaint=null;$('stimulus').setPointerCapture(e.pointerId);paintAt(e)};$('stimulus').onpointermove=e=>{if(painting)paintAt(e)};$('stimulus').onpointerup=()=>{painting=false;priorPaint=null};$('stimulus').oncontextmenu=e=>e.preventDefault();
function drawBrain(){if(!atlas)return;const {x,w,h}=canvas('brain'),filter=$('brainFilter').value,visible=[];for(let i=0;i<atlas.points.length;i++)if(filter==='all'||(filter==='head'&&atlas.point_regions[i]<5)||(filter==='visual'&&atlas.point_regions[i]<=2))visible.push(i);let lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(let i of visible)atlas.points[i].forEach((v,j)=>{lo[j]=Math.min(lo[j],v);hi[j]=Math.max(hi[j],v)});const center=lo.map((v,j)=>(v+hi[j])/2),span=Math.max(...hi.map((v,j)=>v-lo[j]),.1),scale=Math.min(w,h)*.78/span*camera.zoom;projected=[];for(const i of visible){const p=atlas.points[i].map((v,j)=>v-center[j]),a=p[0]*Math.cos(camera.yaw)-p[1]*Math.sin(camera.yaw),z=p[0]*Math.sin(camera.yaw)+p[1]*Math.cos(camera.yaw),b=p[2]*Math.cos(camera.pitch)-z*Math.sin(camera.pitch),depth=p[2]*Math.sin(camera.pitch)+z*Math.cos(camera.pitch);projected.push({i,x:w/2+a*scale,y:h/2+b*scale,z:depth})}projected.sort((a,b)=>a.z-b.z);for(const p of projected){const rate=state?.point_rates_hz?.[p.i]||0;let color=rate===0?'#527784':rate<100?'#69dfd0':rate<200?'#a4eee0':'#f5b36d';x.globalAlpha=rate===0?.30:.88;x.fillStyle=color;x.beginPath();x.arc(p.x,p.y,rate>0?2.1:1.25,0,Math.PI*2);x.fill();if(state?.probe?.id===atlas.point_ids[p.i]){x.globalAlpha=1;x.strokeStyle='#fff';x.lineWidth=1.2;x.beginPath();x.arc(p.x,p.y,6,0,Math.PI*2);x.stroke()}}x.globalAlpha=1}
let drag=null;
$('brain').onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};$('brain').setPointerCapture(e.pointerId)};$('brain').onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>4)drag.moved=true;camera.yaw+=dx*.009;camera.pitch+=dy*.009;drag.x=e.clientX;drag.y=e.clientY;drawBrain()};$('brain').onpointerup=e=>{if(drag&&!drag.moved){const r=$('brain').getBoundingClientRect();let best=null,d=64;for(const p of projected){const q=(p.x-e.clientX+r.left)**2+(p.y-e.clientY+r.top)**2;if(q<d){d=q;best=p}}if(best)command({action:'probe',body_id:atlas.point_ids[best.i]})}drag=null};$('brain').addEventListener('wheel',e=>{e.preventDefault();camera.zoom=Math.max(.5,Math.min(3,camera.zoom*Math.exp(-e.deltaY*.001)));drawBrain()},{passive:false});$('brainFilter').onchange=drawBrain;
function groupMean(sample,prefixes){let a=Object.entries(sample?.groups||{}).filter(([k])=>prefixes.some(p=>k.startsWith(p))).map(([,v])=>v);return a.length?a.reduce((p,c)=>p+c,0)/a.length:0}
function drawRate(){const {x,w,h}=canvas('ratePlot'),history=state?.history||[],series=[s=>s.mean_rate_hz||0,s=>groupMean(s,['T4','T5']),s=>groupMean(s,['Descending'])];const max=Math.max(1,...history.flatMap(s=>series.map(fn=>fn(s)))),end=Math.max(1000,state?.sim_ms||0),start=Math.max(0,end-5000);x.font='9px system-ui';for(let i=0;i<4;i++){let y=10+(h-35)*i/3;x.strokeStyle='#26404d';x.beginPath();x.moveTo(32,y);x.lineTo(w-10,y);x.stroke();x.fillStyle='#8aa4b2';x.fillText((max*(1-i/3)).toFixed(0),2,y+3)}series.forEach((fn,j)=>{x.strokeStyle=colors[j];x.lineWidth=j===0?2:1.3;x.beginPath();history.forEach((s,i)=>{let px=32+(s.sim_ms-start)/(end-start)*(w-42),py=h-25-fn(s)/max*(h-35);if(i)x.lineTo(px,py);else x.moveTo(px,py)});x.stroke()});x.fillStyle='#8aa4b2';x.fillText(`${start} ms`,32,h-5);x.fillText(`${end} ms`,w-60,h-5)}
function drawRaster(){const {x,w,h}=canvas('rasterPlot'),end=Math.max(1000,state?.sim_ms||0),start=Math.max(0,end-1000),n=atlas?.raster_ids.length||1;x.strokeStyle='#253d49';x.font='9px system-ui';x.fillStyle='#8aa4b2';for(let i=0;i<5;i++){const y=10+(h-32)*i/4;x.beginPath();x.moveTo(25,y);x.lineTo(w-10,y);x.stroke();x.fillText(Math.round(n*i/4),2,y)}x.fillStyle='#8de4d9';for(const [t,i] of state?.raster||[]){if(t<start)continue;x.fillRect(25+(t-start)/1000*(w-35),10+i/n*(h-35),1.6,2)}x.fillStyle='#8aa4b2';x.fillText(`${start} ms`,25,h-5);x.fillText(`${end} ms`,w-60,h-5)}
function showResponse(){const s=state?.latest||{},g=s.groups||{};$('meanRate').textContent=(s.mean_rate_hz||0).toFixed(1);$('active').textContent=((s.active_fraction||0)*100).toFixed(1)+'%';$('outputs').replaceChildren();for(const key of ['L1','T4','T5','Descending']){let l=g[key+'_L']||0,r=g[key+'_R']||0,m=Math.max(100,l,r),d=document.createElement('div');d.className='outputrow';const row=document.createElement('div');row.className='row';const name=document.createElement('span');name.textContent=key;const nums=document.createElement('span');nums.textContent=`${l.toFixed(1)} / ${r.toFixed(1)} Hz`;row.append(name,nums);const bars=document.createElement('div');bars.className='pairbars';for(const v of [l,r]){const s=document.createElement('span'),i=document.createElement('i');i.style.width=`${v/m*100}%`;s.append(i);bars.append(s)}d.append(row,bars);$('outputs').append(d)}$('regions').replaceChildren();(atlas?.regions||[]).forEach((name,i)=>{let rate=s.regions?.[i]||0;const d=document.createElement('div');d.className='region';const r=document.createElement('div');r.className='row';const a=document.createElement('span');a.textContent=name;const b=document.createElement('span');b.textContent=rate.toFixed(1)+' Hz';r.append(a,b);const bar=document.createElement('div');bar.className='regionbar';const fill=document.createElement('i');fill.style.width=Math.min(100,rate)+'%';bar.append(fill);d.append(r,bar);$('regions').append(d)})}
function showProbe(){const p=state?.probe;$('pulseProbe').disabled=!p||archived||!controlsReady;if(!p){$('probe').textContent='Select a neuron to see its voltage, spikes and incoming connections.';return}const host=$('probe');host.replaceChildren();const title=document.createElement('strong');title.textContent=`${p.type} · ${p.id} · side ${p.side}`;const values=document.createElement('div');values.className='probevalues';for(const [v,label] of [[p.voltage_mv.toFixed(2),'mV membrane'],[p.chunk_spikes,'spikes / chunk'],[p.incoming_edges,'incoming edges']]){const d=document.createElement('div'),b=document.createElement('strong'),s=document.createElement('div');b.textContent=v;s.textContent=label;d.append(b,s);values.append(d)}const inputs=document.createElement('div');inputs.textContent='Strongest modeled inputs: '+p.strongest_inputs.map(n=>`${n.type} (${n.id}, ${n.weight_mv.toFixed(2)} mV)`).join(' · ');host.append(title,values,inputs)}
async function search(){try{const data=await get('/api/search?q='+encodeURIComponent($('search').value));$('searchResults').replaceChildren();for(const p of data){const b=document.createElement('button');b.textContent=`${p.type} ${p.side} · ${p.id}`;b.onclick=()=>command({action:'probe',body_id:p.id});$('searchResults').append(b)}if(!data.length)$('searchResults').textContent='No matching neuron.'}catch(e){message('Neuron search unavailable.',true)}}$('searchButton').onclick=search;$('search').onkeydown=e=>{if(e.key==='Enter')search()};
function render(){if(!state)return;$('connection').textContent=archived?'Recorded':state.status;$('simtime').textContent=(state.sim_ms||0).toLocaleString();$('datasetBadge').textContent=state.synthetic?'SYNTHETIC DEMO · learning off':'MaleCNS · exploratory · learning off';controlsReady=!!atlas&&!resetting&&!['loading','error','unavailable'].includes(state.status);document.querySelectorAll('[data-control]').forEach(e=>e.disabled=archived||!controlsReady);$('duration').disabled=archived;showResponse();showProbe();if(!painting)drawInput(state.preview||paint);drawBrain();drawRate();drawRaster();$('pulseStatus').textContent=state.pulse_targets?.length?`${state.pulse_targets.length} active pulse(s)`:'No active direct pulse';$('runInfo').textContent=`${archived?'Recorded session':'Current session'}: ${state.run_id||'not started'}\nSimulated time: ${state.sim_ms||0} ms\nBackend: ${state.backend||'recorded'}\nDataset: ${state.dataset||'recorded dataset'}\nMapping: ${state.synthetic?'invented demo coordinates':'exploratory L1 column drive'}\nReward and learning: disabled`;if(state.status==='error')message(state.message,true);if(state.status==='loading')message(state.message)}
async function listRuns(){const runs=await get('/api/runs'),selected=$('record').value;$('record').replaceChildren(new Option('Live controls','live'));for(const r of runs)$('record').append(new Option(`${r.mode==='interactive_exploration'?'Interactive':'Engineering'} · ${r.run_id} · ${r.status}`,r.run_id));$('record').value=selected||'live';lastRuns=Date.now()}
$('record').onchange=async()=>{recordId=$('record').value;archived=recordId!=='live';$('recordMode').textContent=archived?'Recorded':'Live';if(archived){try{const raw=await get(`/api/runs/${recordId}/telemetry`);state=raw.history?raw:{...raw,history:raw.samples||[],latest:(raw.samples||[]).at(-1),preview:Array(768).fill(0),raster:[],point_rates_hz:[],probe:null};state.run_id=recordId;loadForm(state.stimulus);message(raw.history?'Recorded session. Controls are disabled until you return to Live.':'This early engineering run did not record anatomical activity or visual input.');render()}catch(e){message('Recorded data unavailable.',true)}}else{formLoaded=false;message('Live controls restored.');refresh()}};
async function refresh(){if(polling)return;polling=true;try{if(!token)token=(await get('/api/session')).token;if(!atlas){try{atlas=await get('/api/atlas');$('neuronCount').textContent=atlas.neurons.toLocaleString();$('edgeCount').textContent=atlas.edges.toLocaleString();$('mapping').textContent=`${atlas.mapping.mapped_neurons.toLocaleString()} of ${atlas.mapping.total_L1.toLocaleString()} L1 cells have column coordinates. Direct column drive; not calibrated fly vision. Gain is mV per 1 ms tick.`;$('anatomyNote').textContent=atlas.synthetic?`${atlas.display_count} invented node positions. Synthetic teaching fixture; no real fly anatomy.`:`${atlas.display_count.toLocaleString()} sampled anatomical cell landmarks, colored by measured model activity. Not full neuron meshes or live tissue.`;if(atlas.synthetic)$('mapping').textContent='Synthetic teaching network: all 256 nodes, L1/T4/T5 labels, coordinates and edges are invented. Pattern controls demonstrate the software, not fly vision.';for(const g of atlas.groups)$('pulseGroup').append(new Option(`${g.key.replace('_',' · ')} (${g.count})`,g.key));if(atlas.groups.some(g=>g.key==='L1_L'))$('pulseGroup').value='L1_L';$('rasterCaption').textContent=`${atlas.raster_ids.length} sampled neurons · last 1 s`;message('Ready. Choose an input, then Run or Step. You can also send a direct pulse.')}catch(e){}}
if(!archived){state=await get('/api/live');if(!formLoaded&&state.stimulus){loadForm(state.stimulus);formLoaded=true}render()}if(Date.now()-lastRuns>5000)await listRuns()}catch(e){$('connection').textContent='Disconnected';controlsReady=false;document.querySelectorAll('[data-control]').forEach(e=>e.disabled=true);message('Connection unavailable. Check the SSH tunnel or wait for the service to load.',true)}finally{polling=false}}
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName)||archived||!controlsReady)return;if(e.code==='Space'){e.preventDefault();state.status==='running'?command({action:'pause'}):advance({action:'play',duration_ms:+$('duration').value})}if(e.key.startsWith('Arrow')){e.preventDefault();if($('kind').value==='spot'){spot.x=Math.max(0,Math.min(1,spot.x+(e.key==='ArrowRight'?.05:e.key==='ArrowLeft'?-.05:0)));spot.y=Math.max(0,Math.min(1,spot.y+(e.key==='ArrowDown'?.05:e.key==='ArrowUp'?-.05:0)))}else{$('kind').value='grating';$('direction').value=e.key==='ArrowLeft'?'-1':'1'}applyStimulus()}});
window.addEventListener('resize',()=>{drawBrain();drawRate();drawRaster();drawInput(state?.preview||paint)});labels();refresh();setInterval(refresh,250);
